// src/vue/routes/Root.vue
<template>
  <div class="p-4 text-white">
    <RouterLink class="p-2" to="/">home</RouterLink>
    <RouterLink class="p-2" to="/counter">counter</RouterLink>
    <RouterLink class="p-2" to="/todo">todo</RouterLink>
    <RouterLink class="p-2" to="/logo">logo</RouterLink>
  </div>
  <RouterView />
</template>

// src/react/routes/root.jsx
import React from 'react'
import { Outlet, Link } from 'react-router-dom'

function Root () {
  return (
    <div>
      <div className="p-4">
        <Link className="p-2" to='/'>home</Link>
        <Link className="p-2" to='/counter'>counter</Link>
        <Link className="p-2" to='/todo'>todo</Link>
        <Link className="p-2" to='/logo'>logo</Link>
      </div>
      <Outlet />
    </div>
  )
}

export default Root
