// src/react/routes/home.jsx
import React, { useEffect, useState } from "react";
import bouncingLogo from "@/shared/bouncingLogo";
import reactLogo from "@/assets/react.svg";

function Home () {
  const [position, setPosition] = useState(null)

  useEffect(() => {
    const subscriber = (pos) => {
      setPosition(pos)
    }

    bouncingLogo.subscribe(subscriber)
    bouncingLogo.start()

    return () => {
      bouncingLogo.unsubscribe(subscriber)
      bouncingLogo.stop()
    }
  }, [])

  return (
    <>
      <div className="px-6">
        Hello from React!
      </div>
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
          overflow: "hidden",
          zIndex: -1
        }}
      >
        {position && (
          <div
            style={{
              position: "absolute",
              top: position.top,
              left: position.left,
              width: position.width,
              height: position.height,
              borderRadius: "50%",
            }}
          >
            <img
              src={reactLogo}
              width="100%"
            />
          </div>
        )}
      </div>
    </>
  )
}

export default Home;

// src/vue/routes/Home.vue
<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue';
import bouncingLogo from '@/shared/bouncingLogo';
import vueLogo from '@/assets/vue.svg'

const position = ref(null)
const fieldEl = ref(null)

const vueSubscriber = ({ arena, ...logo}) => {
  const field = fieldEl.value?.getBoundingClientRect() || {}

  const pos = {
    ...logo,
    left: logo.left - field.left,
    top: logo.top - field.top
  }

  position.value = pos
}

onMounted(() => {
  console.log("mounted")
  bouncingLogo.subscribe(vueSubscriber)
  bouncingLogo.start()
})

onUnmounted(() => {
  bouncingLogo.unsubscribe(vueSubscriber)
  bouncingLogo.stop()
})


const ballStyle = computed(() => ({
  position: "absolute",
  top: `${position.value?.top}px`,
  left: `${position.value?.left}px`,
  width: `${position.value?.width}px`,
  height: `${position.value?.height}px`,
  borderRadius: '50%',
  display: "grid",
  placeItems: "center"
}))
</script>

<template>
  <div class="px-6">
    Hello from Vue!
  </div>
  <div
    ref="fieldEl"
    :style='{
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      overflow: "hidden",
      zIndex: -1,
    }'
  >
    <div
      v-if="position"
      :style='ballStyle'
    >
      <img
        :src="vueLogo"
        style="width: 100%;"
      />
    </div>
  </div>
</template>
